# Generated by Django 3.1.3 on 2021-10-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20211015_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submit_date',
            field=models.DateField(null=True),
        ),
    ]
